# Generated by Django 4.2.4 on 2023-08-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Машина')),
                ('img', models.ImageField(blank=True, null=True, upload_to='media/cars', verbose_name='Фото Машины')),
                ('dateCreate', models.DateField(auto_now_add=True, null=True, verbose_name='Дата добовление')),
                ('dateUpdate', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменение')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
        ),
    ]
