# Generated by Django 4.2.4 on 2023-08-06 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Бренд машины')),
                ('inform', models.TextField(verbose_name='Информация о бренде ')),
                ('img', models.ImageField(blank=True, null=True, upload_to='brands', verbose_name='Фото')),
                ('date_create', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cars', verbose_name='Тип машины')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
    ]
