# Generated by Django 4.2.4 on 2023-08-11 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_brands'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='slug',
            field=models.SlugField(default=1, max_length=200, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
    ]
