# Generated by Django 4.2.4 on 2023-08-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cars_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='brands',
            name='slug',
            field=models.SlugField(default=1, max_length=200, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
    ]
