# Generated by Django 4.2.4 on 2023-08-11 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_brands_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCompartments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Названия отсека ')),
                ('img', models.ImageField(blank=True, null=True, upload_to='CarCompartments', verbose_name='Фото отсека')),
                ('date_create', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания ')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brands', verbose_name='Бранд к которому относится отсек')),
            ],
            options={
                'verbose_name': 'Отсек машины',
                'verbose_name_plural': 'Отсеки машины',
            },
        ),
    ]
