# Generated by Django 4.2.4 on 2023-08-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_carcompartments'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcompartments',
            name='slug',
            field=models.SlugField(default=32, max_length=200, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
    ]
