# Generated by Django 4.2.4 on 2023-08-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_carcompartments_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcompartments',
            name='brand',
        ),
        migrations.AddField(
            model_name='carcompartments',
            name='brand',
            field=models.ManyToManyField(to='main.brands'),
        ),
    ]
