# Generated by Django 4.2.4 on 2023-08-11 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_carcompartments_brand_carcompartments_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcompartments',
            name='brand',
        ),
        migrations.AddField(
            model_name='carcompartments',
            name='brand',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.brands', verbose_name='Бранд к которому относится отсек'),
            preserve_default=False,
        ),
    ]
