# Generated by Django 4.2.4 on 2023-08-11 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_carcompartments_brand_carcompartments_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carcompartments',
            name='brand',
        ),
    ]
