# Generated by Django 4.2.4 on 2023-08-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_carcompartments_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='')),
                ('img', models.ImageField(blank=True, null=True, upload_to='Details', verbose_name='')),
                ('imgDetails', models.ImageField(blank=True, null=True, upload_to='DetailsDescriptions', verbose_name='')),
                ('partName', models.CharField(max_length=200, verbose_name='')),
                ('partNumber', models.CharField(max_length=200, verbose_name='')),
                ('LR', models.CharField(max_length=200, verbose_name='')),
                ('QTY', models.IntegerField(verbose_name='')),
                ('Remarks', models.TextField(verbose_name='')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brands', verbose_name='')),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carcompartments', verbose_name='')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
