# Generated by Django 4.2.4 on 2023-08-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='details',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name=''),
        ),
    ]
