# Generated by Django 4.2.4 on 2023-08-11 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_details_date_create_details_date_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name': 'Деталь', 'verbose_name_plural': 'Детали'},
        ),
        migrations.AlterField(
            model_name='details',
            name='LR',
            field=models.CharField(max_length=200, verbose_name='LR'),
        ),
        migrations.AlterField(
            model_name='details',
            name='QTY',
            field=models.IntegerField(verbose_name='QTY'),
        ),
        migrations.AlterField(
            model_name='details',
            name='Remarks',
            field=models.TextField(verbose_name='Замечание'),
        ),
        migrations.AlterField(
            model_name='details',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brands', verbose_name='Бренд машины'),
        ),
        migrations.AlterField(
            model_name='details',
            name='compartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carcompartments', verbose_name='Отсек машины'),
        ),
        migrations.AlterField(
            model_name='details',
            name='date_create',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='details',
            name='date_update',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='details',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Details', verbose_name='Фото деталя'),
        ),
        migrations.AlterField(
            model_name='details',
            name='imgDetails',
            field=models.ImageField(blank=True, null=True, upload_to='DetailsDescriptions', verbose_name='Фото подробного описания деталя'),
        ),
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Названия деталя'),
        ),
        migrations.AlterField(
            model_name='details',
            name='partName',
            field=models.CharField(max_length=200, verbose_name='Названия партии'),
        ),
        migrations.AlterField(
            model_name='details',
            name='partNumber',
            field=models.CharField(max_length=200, verbose_name='Номер партии'),
        ),
    ]
