# Generated by Django 4.2.4 on 2023-08-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_details_options_alter_details_lr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='slug',
            field=models.SlugField(default=22, max_length=200, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
    ]
