# Generated by Django 4.2.4 on 2023-08-14 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_details_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='price',
            field=models.CharField(default=2, max_length=200, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
