# Generated by Django 4.2.4 on 2023-08-15 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
