# Generated by Django 4.2.4 on 2023-08-15 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_delete_clients_delete_employees'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brands',
            options={'verbose_name': 'Модель', 'verbose_name_plural': 'Модели'},
        ),
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'Вид Т/С', 'verbose_name_plural': 'Виды Т/С'},
        ),
        migrations.AlterField(
            model_name='brands',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Модели машины'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Вид Т/С'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=200, verbose_name='')),
                ('position', models.CharField(max_length=200, verbose_name='')),
                ('phoneNumber', models.CharField(max_length=200, verbose_name='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
