# Generated by Django 4.2.4 on 2023-08-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_brands_options_alter_cars_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
