# Generated by Django 4.2.4 on 2023-08-16 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_profile_date_update_alter_profile_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Информация о сотруднике', 'verbose_name_plural': 'Информации о сотрудниках'},
        ),
    ]
