# Generated by Django 4.2.4 on 2023-08-18 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_profile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='carcompartments',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.cars', verbose_name='Тип машины'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='details',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brands', verbose_name='Модели машины'),
        ),
    ]
