# Generated by Django 4.2.4 on 2023-08-18 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_carcompartments_car_alter_details_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='LR',
        ),
        migrations.RemoveField(
            model_name='details',
            name='QTY',
        ),
        migrations.RemoveField(
            model_name='details',
            name='Remarks',
        ),
        migrations.RemoveField(
            model_name='details',
            name='partName',
        ),
        migrations.RemoveField(
            model_name='details',
            name='partNumber',
        ),
        migrations.AlterField(
            model_name='details',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brands', verbose_name='Модель машины'),
        ),
    ]
