# Generated by Django 4.2.4 on 2023-08-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_details_lr_remove_details_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcompartments',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Названия отсека '),
        ),
    ]
