# Generated by Django 4.2.4 on 2023-08-18 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_carcompartments_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcompartments',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cars', unique=True, verbose_name='Тип машины'),
        ),
        migrations.AlterField(
            model_name='carcompartments',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Названия отсека '),
        ),
    ]
