# Generated by Django 4.2.4 on 2023-08-18 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_carcompartments_car_alter_carcompartments_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcompartments',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cars', verbose_name='Тип машины'),
        ),
    ]
