# Generated by Django 4.2.4 on 2023-08-18 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_carcompartments_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partName', models.CharField(max_length=200, verbose_name='Название партии')),
                ('partNumber', models.CharField(max_length=200, verbose_name='Номер партии')),
                ('LR', models.CharField(max_length=200, verbose_name='LR')),
                ('QTY', models.IntegerField(verbose_name='Количество')),
                ('Remarks', models.TextField(verbose_name='Замечание')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brands', verbose_name='Модель ТС')),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carcompartments', verbose_name='Отсек машины')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.details', verbose_name='Деталь ')),
            ],
        ),
    ]
