# Generated by Django 4.2.4 on 2023-08-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_detailsinformation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailsinformation',
            options={'verbose_name': 'Информация о партии деталя', 'verbose_name_plural': 'Информации о партиях деталей'},
        ),
        migrations.AlterField(
            model_name='carcompartments',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Названия отсека '),
        ),
    ]
