# Generated by Django 4.2.4 on 2023-09-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_detailsinformation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Названия деталя'),
        ),
    ]
