# Generated by Django 4.2.4 on 2023-09-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_details_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='identifier',
            field=models.CharField(default=1, max_length=200, verbose_name='Номер детали'),
            preserve_default=False,
        ),
    ]
