# Generated by Django 4.2.4 on 2023-09-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_details_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsinformation',
            name='Text',
            field=models.TextField(blank=True, null=True, verbose_name='Данный с excel файла'),
        ),
    ]
