# Generated by Django 4.2.4 on 2023-09-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_detailsinformation_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsinformation',
            name='Text',
        ),
        migrations.AddField(
            model_name='detailsinformation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='detail_files', verbose_name='Excel файл'),
        ),
        migrations.AddField(
            model_name='detailsinformation',
            name='item',
            field=models.IntegerField(default=1, verbose_name='Элемент'),
            preserve_default=False,
        ),
    ]
