# Generated by Django 4.2.4 on 2023-09-21 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_remove_detailsinformation_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('file', models.FileField(upload_to='detailFiles/', verbose_name='Файл')),
                ('date_create', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('date_update', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.brands', verbose_name='Модель ТС')),
                ('compartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.carcompartments', verbose_name='Название отсека')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.details', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Файл деталя',
                'verbose_name_plural': 'Файлы деталей',
            },
        ),
    ]
