# Generated by Django 4.2.4 on 2023-09-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_detailfiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailfiles',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='details',
            name='img',
            field=models.ImageField(default=1, upload_to='Details', verbose_name='Фото деталя'),
            preserve_default=False,
        ),
    ]
