# Generated by Django 4.2.4 on 2023-09-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_alter_detailfiles_name_alter_details_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='Details', verbose_name='Фото деталя'),
        ),
    ]
