# Generated by Django 4.2.4 on 2023-10-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_details_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailfiles',
            name='file_excel',
            field=models.FileField(blank=True, null=True, upload_to='detailFiles/excels', verbose_name='Файл excel'),
        ),
    ]
