# Generated by Django 4.2.4 on 2023-10-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_detailfiles_file_excel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailfiles',
            name='file',
        ),
        migrations.RemoveField(
            model_name='detailfiles',
            name='name',
        ),
    ]
