# Generated by Django 4.2.4 on 2023-10-04 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_remove_detailfiles_file_remove_detailfiles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailfiles',
            name='file',
            field=models.FileField(default=1, upload_to='detailFiles/', verbose_name='Файл'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailfiles',
            name='name',
            field=models.CharField(default=1, max_length=200, verbose_name='Источник'),
            preserve_default=False,
        ),
    ]
