# Generated by Django 4.2.4 on 2024-02-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_detailfiles_file_detailfiles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailsinformation',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='DetailsDescriptions', verbose_name='Фото элемента'),
        ),
    ]
