# Generated by Django 4.2.4 on 2024-03-18 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_detailsinformation_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailfiles',
            name='file_excel',
        ),
    ]
