# Generated by Django 4.2.4 on 2024-03-18 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_remove_detailfiles_file_excel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailsinformation',
            name='file',
        ),
    ]
