# Generated by Django 4.2.12 on 2025-05-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_detailsinformation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailsinformation',
            name='item',
            field=models.CharField(max_length=200, verbose_name='Элемент'),
        ),
    ]
